import HomePage from "@/components/home/homePage/HomePage";
import Head from "next/head";
import "../styles/global.scss"



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <HomePage/>
  
    </>
  );
}
