import Head from "next/head";
import Success from "@/components/home/success/Success";



export default function SuccessPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <Success/>
  
    </>
  );
}
